before_script:
  - npm install
  - npm i -g @gapi/cli
  - npm i -g ts-node
  - npm i -g typescript
script: gapi microservices findUser & gapi microservices deleteUser & npm start & npm test
env:
  - DEPLOY_PLATFORM=heroku
language: node_js
node_js:
  - "8"
